apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: status-reporter
rules:
  - apiGroups:
      - ocs.openshift.io
    resources:
      - storageclients
    verbs:
      - get
      - list
      - patch
  - apiGroups:
      - ""
    resources:
      - configmaps
    resourceNames:
      - rook-ceph-mon-endpoints
    verbs:
      - get
      - list
      - update
  - apiGroups:
      - config.openshift.io
    resources:
      - clusterversions
      - dns
    verbs:
      - get
      - list
